### ISSUE TITLE
Web Screen Size

### ISSUE THREAD

**Issue by joeyoropesa-dev** [someone5678/YouTubeTVUI#1]
Is there any script how to fix YouTube on TV Webview size so that it can automatically fit the size of the screen and app without being forced to go into full screen mode to get fully sized YouTube on TV

**Comment by someone5678** [comment]
> Is there any script how to fix YouTube on TV Webview size so that it can automatically fit the size of the screen and app without being forced to go into full screen mode to get fully sized YouTube on TV

As my javascript knowledge is very limited, I have not much idea about that.
Also, this forced full screen mode is intended as this program's main purpose is usage in Steam Deck's gaming mode session.

**Comment by joeyoropesa-dev** [comment]
> > Is there any script how to fix YouTube on TV Webview size so that it can automatically fit the size of the screen and app without being forced to go into full screen mode to get fully sized YouTube on TV
> 
> As my javascript knowledge is very limited, I have not much idea about that.
> Also, this forced full screen mode is intended as this program's main purpose is usage in Steam Deck's gaming mode session.
> 

Well, can you at least use the help of AI to develop the script for fixing that screen size on the web.
